export const i18n = {
    layout: {
        operation: 'Operação',
        panel: 'Painel',
        user: 'Usuário',
        changesAndIms: 'Changes e IMs',
        logout: 'Sair',
        openMenu: 'Abrir menu',
        closeMenu: 'Fechar menu',
        headerTitle: 'Acompanhamento operacional',
        updated: 'Atualizado',
        appTitle: 'Gerenciador de Mudanças',
    },
    gmuds: {
        title: 'Projetos e changes',
        changes: 'Changes',
        completed: 'Concluídas',
        pending: 'Pendentes',
        resolvedIms: 'IMs resolvidas',
        projects: 'Projetos',
        latestIms: 'Últimos IMs',
        new: 'Novo',
        edit: 'Editar',
        ims: 'IMs',
        createPage: {
            eyebrow: 'Cadastro da planilha',
            title: 'Novo registro de projeto e change',
            description: 'Formulário adaptado para os mesmos campos usados no controle operacional.',
            projectData: 'Dados do projeto',
            projectDataDescription: 'Identificação principal da linha da planilha.',
            required: 'Obrigatório',
            projectNamePlaceholder: 'Ex: Parcerias – Tabela de dados de adesão da Sura',
            projectNumberPlaceholder: 'PRJ0304753',
            sprintPlaceholder: 'Sprint 6 - Parcerias',
            changeNumberPlaceholder: 'CHG0070521',
            projectType: 'Tipo de Projeto',
            ownersAndExecution: 'Responsáveis e execução',
            ownersAndExecutionDescription: 'Campos da parte operacional da planilha.',
            novaDeveloper: 'Desenvolvedor Nova',
            novaDeveloperPlaceholder: 'Nome do desenvolvedor',
            brasilsegOwner: 'Responsável BrasilSeg',
            brasilsegOwnerPlaceholder: 'Nome do responsável',
            assignmentGroup: 'Grupo de Atribuição',
            assignmentGroupPlaceholder: 'Parcerias - Aplicação',
            imNumber: 'Número de IM',
            imNumberPlaceholder: 'INC0651160',
            openedAt: 'Data de Abertura',
            closedAt: 'Data de Fechamento',
            jobNotes: 'JOB / Observações',
            jobNotesPlaceholder: 'Descreva a atividade operacional vinculada à change',
            saveDraft: 'Salvar rascunho',
            createRecord: 'Criar registro',
            goal: 'Objetivo',
            goalDescription: 'Centralizar o conteúdo das planilhas em um cadastro visual e organizado.',
            checklistTitle: 'Checklist antes de enviar',
            checklist: [
                'Preencher nome e número do projeto',
                'Informar número da change e sprint',
                'Definir responsáveis Nova e BrasilSeg',
                'Vincular IM, datas e observações operacionais',
            ],
        },
        editPage: {
            eyebrow: 'Edição',
            notFound: 'Registro não encontrado',
            notFoundDescription: 'Selecione uma GMUD válida para editar os dados operacionais.',
            titlePrefix: 'Editar',
            description: 'Atualize os dados da change com mais contexto, responsáveis e observações.',
            currentStatus: 'Status atual',
            linkedIms: 'IMs vinculados',
            mainData: 'Dados principais',
            mainDataDescription: 'Informações centrais da GMUD para manutenção do registro.',
            changeNumber: 'Número da Change',
            projectNumber: 'Número do Projeto',
            changeStatus: 'Status Change',
            projectType: 'Tipo de Projeto',
            typeFix: 'Fix',
            typeProject: 'Implantação/Projeto',
            owners: 'Responsáveis',
            ownersDescription: 'Ajuste os contatos principais e o acompanhamento do item.',
            novaDeveloper: 'Desenvolvedor Nova',
            brasilsegOwner: 'Responsável BrasilSeg',
            notes: 'Observações',
            notesTemplatePrefix: 'Change',
            notesTemplateSuffix: 'em acompanhamento operacional.',
            back: 'Voltar',
            save: 'Salvar alterações',
            quickSummary: 'Resumo rápido',
            type: 'Tipo',
            status: 'Status',
            owner: 'Responsável',
            relatedIms: 'IMs relacionadas',
            noRelatedIms: 'Nenhuma IM vinculada para esta change.',
            addImTitle: 'Adicionar IM',
            addImDescription: 'Cadastre uma IM vinculada de forma simples e rápida.',
            imNumber: 'Número de IM',
            assignmentGroup: 'Grupo de Atribuição',
            imStatus: 'Status IM',
            job: 'JOB',
            addImButton: 'Adicionar IM',
            imAdded: 'IM adicionada com sucesso.',
            validationSummary: 'Revise os campos obrigatórios da IM.',
            validationImNumber: 'Informe um número de IM válido.',
            validationAssignmentGroup: 'Informe o grupo de atribuição.',
            validationJob: 'Informe o JOB da IM.',
        },
        table: {
            projectName: 'Nome do Projeto',
            project: 'Projeto',
            sprint: 'Sprint',
            change: 'Change',
            status: 'Status',
            type: 'Tipo',
            nova: 'Nova',
            brasilseg: 'BrasilSeg',
            actions: 'Ações',
            group: 'Grupo',
            im: 'IM',
            openedAt: 'Abertura',
        },
    },
    login: {
        secureAccess: 'Acesso seguro',
        title: 'Acessar sistema',
        description: 'Plataforma moderna para abertura, gestão e acompanhamento de GMUDs.',
        email: 'E-mail',
        emailPlaceholder: 'usuario@empresa.com',
        password: 'Senha',
        enter: 'Entrar',
        configureUser: 'Configurar usuário',
    },
    userSettings: {
        title: 'Gestão de usuários',
        description: 'Administradores podem cadastrar e acompanhar outros usuários do sistema.',
        registerTitle: 'Cadastrar novo usuário',
        registerDescription: 'Preencha os dados e defina o perfil de acesso.',
        name: 'Nome',
        email: 'E-mail',
        password: 'Senha',
        role: 'Perfil',
        create: 'Cadastrar usuário',
        submitting: 'Cadastrando...',
        listTitle: 'Usuários cadastrados',
        listDescription: 'Relação de acessos disponíveis no sistema.',
        loading: 'Carregando usuários...',
        empty: 'Nenhum usuário cadastrado até o momento.',
        createdSuccess: 'Usuário cadastrado com sucesso.',
        validation: 'Preencha nome, e-mail e senha para continuar.',
        loadError: 'Não foi possível carregar os usuários.',
        submitError: 'Não foi possível cadastrar o usuário.',
        accessDenied: 'Somente administradores podem cadastrar outros usuários.',
        statusActive: 'Ativo',
        statusInactive: 'Inativo',
        table: {
            name: 'Nome',
            email: 'E-mail',
            role: 'Perfil',
            status: 'Status',
        },
        roles: {
            admin: 'Administrador',
            manager: 'Gestor',
            common: 'Comum',
        },
    },
    incidents: {
        title: 'IMs',
        notFound: 'Registro não encontrado',
        notFoundDescription:
            'Selecione uma change válida na listagem principal para visualizar os incidentes.',
        details: 'Detalhamento limpo dos incidentes vinculados.',
        project: 'Projeto',
        sprint: 'Sprint',
        status: 'Status',
        owner: 'Responsável',
        sheetTitle: 'Planilha de IMs',
        editChange: 'Editar change',
        empty: 'Nenhum IM vinculado a esta change até o momento.',
        table: {
            assignmentGroup: 'Grupo de Atribuição',
            imNumber: 'Número de IM',
            imStatus: 'Status IM',
            openedAt: 'Data de Abertura',
            closedAt: 'Data de Fechamento',
            job: 'JOB',
            action: 'Ação',
            editIm: 'Editar IM',
        },
    },
}
