export declare const i18n: {
    layout: {
        operation: string
        panel: string
        user: string
        changesAndIms: string
        logout: string
        openMenu: string
        closeMenu: string
        headerTitle: string
        updated: string
        appTitle: string
    }
    gmuds: {
        title: string
        changes: string
        completed: string
        pending: string
        resolvedIms: string
        projects: string
        latestIms: string
        new: string
        edit: string
        ims: string
        createPage: {
            eyebrow: string
            title: string
            description: string
            projectData: string
            projectDataDescription: string
            required: string
            projectNamePlaceholder: string
            projectNumberPlaceholder: string
            sprintPlaceholder: string
            changeNumberPlaceholder: string
            projectType: string
            ownersAndExecution: string
            ownersAndExecutionDescription: string
            novaDeveloper: string
            novaDeveloperPlaceholder: string
            brasilsegOwner: string
            brasilsegOwnerPlaceholder: string
            assignmentGroup: string
            assignmentGroupPlaceholder: string
            imNumber: string
            imNumberPlaceholder: string
            openedAt: string
            closedAt: string
            jobNotes: string
            jobNotesPlaceholder: string
            saveDraft: string
            createRecord: string
            goal: string
            goalDescription: string
            checklistTitle: string
            checklist: string[]
        }
        editPage: {
            eyebrow: string
            notFound: string
            notFoundDescription: string
            titlePrefix: string
            description: string
            currentStatus: string
            linkedIms: string
            mainData: string
            mainDataDescription: string
            changeNumber: string
            projectNumber: string
            changeStatus: string
            projectType: string
            typeFix: string
            typeProject: string
            owners: string
            ownersDescription: string
            novaDeveloper: string
            brasilsegOwner: string
            notes: string
            notesTemplatePrefix: string
            notesTemplateSuffix: string
            back: string
            save: string
            quickSummary: string
            type: string
            status: string
            owner: string
            relatedIms: string
            noRelatedIms: string
            addImTitle: string
            addImDescription: string
            imNumber: string
            assignmentGroup: string
            imStatus: string
            job: string
            addImButton: string
            imAdded: string
            validationSummary: string
            validationImNumber: string
            validationAssignmentGroup: string
            validationJob: string
        }
        table: {
            projectName: string
            project: string
            sprint: string
            change: string
            status: string
            type: string
            nova: string
            brasilseg: string
            actions: string
            group: string
            im: string
            openedAt: string
        }
    }
    login: {
        secureAccess: string
        title: string
        description: string
        email: string
        emailPlaceholder: string
        password: string
        enter: string
        configureUser: string
    }
    userSettings: {
        title: string
        description: string
        registerTitle: string
        registerDescription: string
        name: string
        email: string
        password: string
        role: string
        create: string
        submitting: string
        listTitle: string
        listDescription: string
        loading: string
        empty: string
        createdSuccess: string
        validation: string
        loadError: string
        submitError: string
        accessDenied: string
        statusActive: string
        statusInactive: string
        table: {
            name: string
            email: string
            role: string
            status: string
        }
        roles: {
            admin: string
            manager: string
            common: string
        }
    }
    incidents: {
        title: string
        notFound: string
        notFoundDescription: string
        details: string
        project: string
        sprint: string
        status: string
        owner: string
        sheetTitle: string
        editChange: string
        empty: string
        table: {
            assignmentGroup: string
            imNumber: string
            imStatus: string
            openedAt: string
            closedAt: string
            job: string
            action: string
            editIm: string
        }
    }
}
